### ISSUE TITLE
[ANTLR] expression should take indexIdentifier not expression LBRACKET expression RBRACKET

### ISSUE THREAD

**Issue by godott** [Qiskit/openqasm#182]
In the grammar(https://qiskit.github.io/openqasm/grammar/index.html)
`
expression:
...
 | expression LBRACKET expression RBRACKET
|...
`

It will incorrectly match strings like `1+2[3]`. It should be indexIdentifier instead.

**Comment by hhorii** [comment]
You may refer an obsolete g4 file but the latest still allows `1+2[3];` in `expressionTerminator` [here](https://github.com/Qiskit/openqasm/blob/master/source/grammar/qasm3.g4#L347).

However, I guess that `expression LBRACKET expression RBRACKET` is necessary because subroutine or kernel calls can return `bit[n]` and their caller can access its element.

I know they are issues in the current g4 but this kind of errors will be identified after parsing.

**Comment by godott** [comment]
Sounds reasonable.
